import React, { Component } from 'react';
import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  DeviceEventEmitter,
} from 'react-native';
import { connect } from 'react-redux';
import Swipeable from 'react-native-swipeable';
import Ionicons from 'react-native-vector-icons/Ionicons';
import { Divider } from 'react-native-elements';
import { Kaede } from 'react-native-textinput-effects';
import { Container, Header, Content, Body, Title, Button, Left, Icon, Right } from 'native-base';
import DateTimePicker from 'react-native-modal-datetime-picker';
import PushNotification from 'react-native-push-notification';

import { fetchRecipes, addItem, removeItem, addItemArray } from '../redux/actions';

import { colors } from '../utils/constants';

class SelectionScreen extends Component {
  state = {
    currentlyOpenSwipeable: null,
    value: '',
    isDateTimePickerVisible: false,
    items: [],
    item: {},
    expirationDate: [],
  };

  componentDidMount() {
    PushNotification.localNotificationSchedule({
      message: "You still haven't consumed Salmon :(", // (required)
      /* Android Only Properties */
      id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText:
        'Eating salmon regularly reduces the risk of depression. Check out these recipes with salmon!', // (optional) default: "message" prop
      subText: 'Salmon reduces risk of depression!', // (optional) default: none
      color: 'red', // (optional) default: system default
      actions: '["Check out"]',
      date: new Date(Date.now() + 25 * 1000), // in 60 secs
    });

    // Register all the valid actions for notifications here and add the action handler for each action
    PushNotification.registerNotificationActions(['Check out', 'Reject', 'Yes', 'No']);
    DeviceEventEmitter.addListener('notificationActionReceived', action => {
      console.log('Notification action received: ' + action);
      const info = JSON.parse(action.dataJSON);
      if (info.action == 'Check out') {
        // Do work pertaining to Accept action here
        this.props.fetchRecipes('Salmon');
        setTimeout(() => {
          this.props.navigation.navigate('Recipes');
        }, 1000);
      } else if (info.action == 'Reject') {
        // Do work pertaining to Reject action here
        console.log('NOOOOO');
      }
      // Add all the required actions handlers
    });
  }

  /* Text Input */
  onInputChange = text => {
    this.setState({ value: text });
  };
  onInputEnter = () => {
    let newItem = { name: this.state.value, checked: false, expDate: 'None' };
    //this.props.addItem(newItem);
    this.setState(
      (prevState, props) => ({ items: [newItem, ...prevState.items], value: '', item: newItem }),
      () => console.log(this.state.items),
    );
  };
  /* ================================================================================= */
  /* Item Remove Button */
  onItemRemove = selectedItem => {
    // const newItemsArray = this.props.items.filter(item => item.name !== selectedItem.name);
    // this.setState((prevState, props) => ({
    //   items: newItemsArray,
    // }));
  };
  /* ================================================================================= */
  /* Done Button */
  onBtnPress = () => {
    this.props.navigation.navigate('Groceries');

    this.props.addItemArray(this.state.items);
  };
  /* ================================================================================= */
  handleScroll = () => {
    const { currentlyOpenSwipeable } = this.state;

    if (currentlyOpenSwipeable) {
      currentlyOpenSwipeable.recenter();
    }
  };
  /* ================================================================================= */
  /* Pick a date */
  showDateTimePicker = () => this.setState({ isDateTimePickerVisible: true });
  hideDateTimePicker = () => this.setState({ isDateTimePickerVisible: false });
  handleDatePicked = date => {
    this.setState({ item: { ...this.state.item, expDate: date } });
    this.hideDateTimePicker();
    setTimeout(() => {
      this.props.addItem(this.state.item);
    }, 1000);
  };
  /* ================================================================================= */

  render() {
    const { currentlyOpenSwipeable } = this.state;
    const itemProps = {
      onOpen: (event, gestureState, swipeable) => {
        if (currentlyOpenSwipeable && currentlyOpenSwipeable !== swipeable) {
          currentlyOpenSwipeable.recenter();
        }

        this.setState({ currentlyOpenSwipeable: swipeable });
      },
      onClose: () => this.setState({ currentlyOpenSwipeable: null }),
    };

    return (
      <Container>
        <Header>
          <Body>
            <Title>Groceries List</Title>
          </Body>
        </Header>

        <View style={styles.container}>
          <ScrollView onScroll={this.handleScroll}>
            <View style={styles.titleWrapper}>
              <Text style={styles.title}>Enter groceries that you currently have:</Text>
            </View>

            <View style={styles.itemInputWrapper}>
              <Kaede
                label="Enter a new item"
                value={this.state.value}
                onChangeText={this.onInputChange}
                onSubmitEditing={this.onInputEnter}
                labelStyle={{
                  color: 'white',
                  backgroundColor: '#fcb794',
                }}
                inputStyle={{
                  color: 'white',
                  backgroundColor: '#8781bd',
                }}
              />
            </View>

            {this.state.items.map(item => (
              <View style={styles.wrapper} key={item.name}>
                <Swipeable
                  leftButtonWidth={60}
                  leftButtons={[
                    <TouchableOpacity
                      style={[styles.leftSwipeItem, { backgroundColor: 'lightseagreen' }]}
                      onPress={this.showDateTimePicker}
                    >
                      <Ionicons
                        style={{ backgroundColor: 'transparent' }}
                        name="ios-calendar"
                        size={35}
                        color="white"
                      />
                    </TouchableOpacity>,
                  ]}
                  rightButtons={[
                    <TouchableOpacity
                      style={[styles.rightSwipeItem, { backgroundColor: 'lightseagreen' }]}
                    >
                      <Ionicons
                        style={{ backgroundColor: 'transparent' }}
                        name="ios-checkmark-circle-outline"
                        size={35}
                        color="white"
                      />
                    </TouchableOpacity>,
                    <TouchableOpacity
                      style={[styles.rightSwipeItem, { backgroundColor: 'orchid' }]}
                      onPress={() => {
                        this.setState({
                          items: this.state.items.filter(arrItem => arrItem.name !== item.name),
                        });
                        this.props.removeItem(item);
                      }}
                    >
                      <Ionicons
                        style={{ backgroundColor: 'transparent' }}
                        name="ios-close-circle-outline"
                        size={35}
                        color="white"
                      />
                    </TouchableOpacity>,
                  ]}
                  onRightButtonsOpenRelease={itemProps.onOpen}
                  onRightButtonsCloseRelease={itemProps.onClose}
                >
                  <View style={[styles.listItem, { backgroundColor: '#8781bd' }]}>
                    <Text style={{ fontSize: 20, color: '#fff' }}>{item.name}</Text>
                  </View>
                </Swipeable>
              </View>
            ))}
          </ScrollView>

          <DateTimePicker
            isVisible={this.state.isDateTimePickerVisible}
            onConfirm={this.handleDatePicked}
            onCancel={this.hideDateTimePicker}
          />

          <View style={styles.btnWrapper}>
            <Button block onPress={this.onBtnPress}>
              <Text style={{ fontSize: 20, color: '#fff' }}>Done</Text>
            </Button>
          </View>
        </View>
      </Container>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  wrapper: {},
  listItem: {
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.5)',
  },
  leftSwipeItem: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 20,
  },
  rightSwipeItem: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: 20,
  },
  titleWrapper: {
    marginTop: 10,
    marginBottom: 15,
    marginHorizontal: 10,
  },
  title: {
    fontSize: 18,
  },
  itemInputWrapper: {
    marginBottom: 20,
  },
  btnWrapper: {
    position: 'absolute',
    width: '80%',
    top: 500,
    justifyContent: 'center',
    alignSelf: 'center',
  },
});

const mapStateToProps = state => ({
  items: state.items,
});

export default connect(mapStateToProps, { fetchRecipes, addItem, removeItem, addItemArray })(
  SelectionScreen,
);
