import React, { Component } from 'react';
import Ionicons from 'react-native-vector-icons/Ionicons';
import { StyleSheet, View, Text, Image } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import AppIntroSlider from 'react-native-app-intro-slider';
import PushNotification from 'react-native-push-notification';

const styles = StyleSheet.create({
  mainContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  image: {
    width: 320,
    height: 320,
  },
  text: {
    color: 'rgba(255, 255, 255, 0.8)',
    backgroundColor: 'transparent',
    textAlign: 'center',
    paddingHorizontal: 16,
    fontSize: 26,
  },
  title: {
    fontSize: 32,
    color: 'white',
    backgroundColor: 'transparent',
    textAlign: 'center',
    marginBottom: 16,
  },
});

const slides = [
  {
    key: 'somethun',
    title: 'Welcome!',
    text: 'Keep track of your groceries in one place!',
    icon: 'ios-pizza',
    colors: ['#63E2FF', '#B066FE'],
  },
  {
    key: 'somethun1',
    title: '',
    text: 'Receive recipe suggestions based on available food products!',
    icon: 'ios-paper-outline',
    colors: ['#A3A1FF', '#3A3897'],
  },
  {
    key: 'somethun2',
    title: 'Enjoy the app!',
    text: 'Visualize nutrition information of consumed products!',
    icon: 'ios-pie-outline',
    colors: ['#29ABE2', '#4F00BC'],
  },
];

export default class WelcomeScreen extends Component {
  componentDidMount() {
    PushNotification.localNotificationSchedule({
      message: "You still haven't consumed Salmon :(", // (required)
      /* Android Only Properties */
      id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: 'My Notification Ticker', // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText:
        'Eating salmon regularly reduces the risk of depression. Check out these recipes with salmon!', // (optional) default: "message" prop
      subText: 'Salmon reduces risk of depression!', // (optional) default: none
      color: 'red', // (optional) default: system default

      date: new Date(Date.now() + 5 * 1000), // in 60 secs
    });
  }

  onDone = () => {
    this.props.navigation.navigate('Setup');
  };

  _renderItem = props => (
    <LinearGradient
      style={[
        styles.mainContent,
        {
          paddingTop: props.topSpacer,
          paddingBottom: props.bottomSpacer,
        },
      ]}
      colors={props.colors}
      start={{ x: 0, y: 0.1 }}
      end={{ x: 0.1, y: 1 }}
    >
      <Ionicons
        style={{ backgroundColor: 'transparent' }}
        name={props.icon}
        size={200}
        color="white"
      />
      <View>
        <Text style={styles.title}>{props.title}</Text>
        <Text style={styles.text}>{props.text}</Text>
      </View>
    </LinearGradient>
  );

  render() {
    return (
      <AppIntroSlider
        slides={slides}
        renderItem={this._renderItem}
        bottomButton
        onDone={this.onDone}
      />
    );
  }
}
