# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroceryTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GroceryTracker
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'GroceryTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GroceryTracker-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GroceryTracker-tvOS

  target 'GroceryTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
