import React, { Component } from 'react';
import { TouchableOpacity, DeviceEventEmitter } from 'react-native';
import {
  Container,
  Content,
  Card,
  CardItem,
  Text,
  Icon,
  Right,
  Left,
  CheckBox,
  Fab,
  Button,
} from 'native-base';
import Prompt from 'rn-prompt';
import { connect } from 'react-redux';
import PushNotification from 'react-native-push-notification';

import { fetchRecipes, addItemArray, addItem, addHealthyItem, removeItem } from '../redux/actions';

class HealthyFood extends Component {
  state = {
    selectedItems: [],
    active: false,
    promptVisible: false,
    promtValue: {},
  };

  componentDidMount() {
    if (this.props.items.some(e => e.name === 'salmon')) {
      if (!this.props.consumed.healthyFood.some(e => e.name === 'salmon')) {
        PushNotification.localNotificationSchedule({
          message: "You still haven't consumed Salmon :(", // (required)
          /* Android Only Properties */
          id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
          autoCancel: true, // (optional) default: true
          largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
          smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
          bigText:
            'Eating salmon regularly reduces the risk of depression. Check out these recipes with salmon!', // (optional) default: "message" prop
          subText: 'Salmon reduces risk of depression!', // (optional) default: none
          color: 'red', // (optional) default: system default
          actions: '["Check out"]',
          date: new Date(Date.now() + 40 * 1000), // in 60 secs
        });

        // Register all the valid actions for notifications here and add the action handler for each action
        PushNotification.registerNotificationActions(['Check out', 'Reject', 'Yes', 'No']);
        DeviceEventEmitter.addListener('notificationActionReceived', action => {
          console.log('Notification action received: ' + action);
          const info = JSON.parse(action.dataJSON);
          if (info.action == 'Check out') {
            // Do work pertaining to Accept action here
            this.props.fetchRecipes('Salmon');
            setTimeout(() => {
              this.props.navigation.navigate('Recipes');
            }, 1000);
          } else if (info.action == 'Reject') {
            // Do work pertaining to Reject action here
            console.log('NOOOOO');
          }
          // Add all the required actions handlers
        });
      }
    }
  }

  /* Item Press */
  onItemPress(checkedItem) {
    const newItems = this.props.items.map(
      item => (item.name === checkedItem.name ? { name: item.name, checked: !item.checked } : item),
    );
    this.props.addItemArray(newItems);
    setTimeout(() => {
      this.setState({
        selectedItems: this.props.items.filter(i => i.checked),
      });
    }, 500);
  }
  /* ================================================================================= */
  /* FAB Button */
  onSearchPress = () => {
    console.log(this.state.selectedItems);
    let itemsNames = this.state.selectedItems.map(item => item.name);
    const query = itemsNames.join('+');
    console.log(query);
    this.props.fetchRecipes(query);
    setTimeout(() => {
      this.props.navigation.navigate('Recipes');
    }, 1000);
  };
  onAddPress = () => {
    this.setState({ promptVisible: true });
  };
  onConsumePress = () => {
    this.state.selectedItems.map(item => this.props.removeItem(item));
    this.props.addHealthyItem(this.state.selectedItems);
    this.setState({ selectedItems: [] });
  };
  /* ================================================================================= */
  /* Promt Button */
  onPromtSubmit = value => {
    this.setState({
      promptVisible: false,
      promtValue: { name: value },
    });
    this.props.addItem({ name: value });
  };
  onPromtCancel = () => {
    this.setState({
      promptVisible: false,
    });
  };
  /* ================================================================================= */
  render() {
    return (
      <Container>
        <Content>
          {this.props.items
            .filter(
              i =>
                i.name === 'eggs' ||
                i.name === 'tomatoes' ||
                i.name === 'potatoes' ||
                i.name === 'salmon' ||
                i.name === 'garlic' ||
                i.name === 'broccoli' ||
                i.name === 'shrimps' ||
                i.name === 'lemons' ||
                i.name === 'dark chocolate' ||
                i.name === 'apples' ||
                i.name === 'milk' ||
                i.name === 'bananas' ||
                i.name === 'grapes' ||
                i.name === 'oranges' ||
                i.name === 'kiwis' ||
                i.name === 'strawberries' ||
                i.name === 'vegetables' ||
                i.name === 'fruits' ||
                i.name === 'chicken' ||
                i.name === 'turkey' ||
                i.name === 'pork' ||
                i.name === 'beans',
            )
            .map(item => (
              <Card key={item.name}>
                <CardItem style={{ backgroundColor: '#5fb660' }}>
                  <Left>
                    <CheckBox
                      checked={item.checked}
                      color="#fff"
                      onPress={this.onItemPress.bind(this, item)}
                    />
                  </Left>

                  <TouchableOpacity onPress={this.onItemPress.bind(this, item)}>
                    <Text style={{ color: '#fff', fontSize: 20 }}>{item.name}</Text>
                  </TouchableOpacity>

                  <Right>
                    <TouchableOpacity onPress={this.onItemPress.bind(this, item)}>
                      <Icon name="arrow-forward" />
                    </TouchableOpacity>
                  </Right>
                </CardItem>
              </Card>
            ))}
        </Content>
        <Fab
          active={this.state.active}
          direction="up"
          containerStyle={{}}
          style={{ backgroundColor: '#5067FF' }}
          position="bottomRight"
          onPress={() => this.setState({ active: !this.state.active })}
        >
          <Icon name="menu" />
          <Button style={{ backgroundColor: '#DD5144' }} onPress={this.onSearchPress}>
            <Icon name="search" style={{ fontSize: 25 }} />
          </Button>
          <Button style={{ backgroundColor: '#3B5998' }} onPress={this.onAddPress}>
            <Icon name="add" style={{ fontSize: 30 }} />
          </Button>
          <Button style={{ backgroundColor: '#34A34F' }} onPress={this.onConsumePress}>
            <Icon name="checkmark" style={{ fontSize: 30 }} />
          </Button>
        </Fab>

        <Prompt
          title="Add new item"
          placeholder=""
          defaultValue=""
          textInputProps={{ autoCapitalize: 'none', autoCorrect: false }}
          visible={this.state.promptVisible}
          onCancel={this.onPromtCancel}
          onSubmit={this.onPromtSubmit}
        />
      </Container>
    );
  }
}

const mapStateToProps = state => ({
  items: state.items,
  consumed: state.consumed,
});

export default connect(mapStateToProps, {
  fetchRecipes,
  addItemArray,
  addItem,
  addHealthyItem,
  removeItem,
})(HealthyFood);
